[build]
  base = "./static-2025"
  publish = ""
  command = ""

# https://cli.netlify.com/netlify-dev#netlifytoml-dev-block
[dev]
  command = "npm run dev"
  autoLaunch = false

# Redirect the default subdomain to the primary domain
[[redirects]]
  from = "https://200ok.netlify.app/*"
  to = "https://200ok.us/:splat"
  status = 301
  force = true

[[redirects]]
  from = "/submit"
  to = "https://sessionize.com/200ok-2025/"
  status = 302
  force = true

[[redirects]]
  from = "/tickets"
  to = "https://www.techlahoma.org/tickets-arent-available"
  status = 302
  force = true

[[redirects]]
  from = "/survey"
  to = "https://docs.google.com/forms/d/e/1FAIpQLSe85ht7bkrJ8UuNVl02Gl6tHz4KAM_DzDFrVGyufyhYXJt_bA/viewform?usp=header"
  status = 302
  force = true

[[redirects]]
  from = "/network"
  to = "https://zoom.us/j/92474087693"
  status = 302
  force = true

[[redirects]]
  from = "/watch"
  to = "https://youtu.be/2R5k0Q_sZt0"
  status = 302
  force = true

[[redirects]]
  from = "/stream"
  to = "https://youtu.be/2R5k0Q_sZt0"
  status = 302
  force = true
